// Optional browser QA: requires Playwright and an installed Chromium browser.
const { chromium } = require('playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({headless:true, ...(process.env.QA_BROWSER ? {executablePath:process.env.QA_BROWSER} : {})});
  const info = JSON.parse(fs.readFileSync(path.join(__dirname, 'dist/build-info.json')));
  const origin = (process.env.QA_ORIGIN || 'http://127.0.0.1:4173') + info.base;
  const report = {viewports:[], checks:[]};
  const errors = [];
  fs.mkdirSync(path.join(__dirname,'qa'),{recursive:true});
  const page = await browser.newPage();
  page.on('pageerror', error => errors.push(error.message));
  for (const width of [1440, 390, 320, 768]) {
    await page.setViewportSize({width,height:1000});
    for (const route of [...info.routes, '404.html']) {
      const response = await page.goto(origin + route);
      assert.equal(response.status(), 200);
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
      assert.equal(overflow, false, `Overflow ${width}: ${route}`);
    }
    report.viewports.push({width,pages:info.routes.length+1,noOverflow:true});
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(origin);
  await page.screenshot({path:path.join(__dirname,'qa/home-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(origin);
  await page.screenshot({path:path.join(__dirname,'qa/home-mobile.png'),fullPage:true});
  const menu = page.locator('.menu-toggle');
  await menu.click();
  assert.equal(await menu.getAttribute('aria-expanded'),'true');
  assert.equal(await page.locator('#primary-nav').isVisible(),true);
  await page.keyboard.press('Escape');
  assert.equal(await menu.getAttribute('aria-expanded'),'false');
  assert.equal(await page.evaluate(() => document.activeElement.className),'menu-toggle');
  await menu.click();
  await page.locator('main h1').click();
  assert.equal(await menu.getAttribute('aria-expanded'),'false');
  await menu.click();
  await page.locator('#primary-nav').getByRole('link',{name:'Apps',exact:true}).click();
  assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');
  report.checks.push('Mobile open, Escape/focus, outside click, navigation');
  await page.locator('#app-search').fill('document');
  assert.equal(await page.locator('[data-app]:visible').count(),1);
  await page.locator('#app-search').fill('no-such-app');
  assert.equal(await page.locator('#empty-apps').isVisible(),true);
  await page.locator('#app-search').fill('');
  await page.getByRole('button',{name:'Lifestyle',exact:true}).click();
  assert.equal(await page.locator('[data-app]:visible').count(),1);
  assert.equal(await page.locator('[data-app]:visible').getAttribute('data-category'),'Lifestyle');
  await page.getByRole('button',{name:'All',exact:true}).click();
  assert.equal(await page.locator('[data-app]:visible').count(),info.appCount);
  report.checks.push('Search, empty state, category and reset');
  await page.goto(origin + 'contact/');
  await page.locator('#contact-name').fill('QA User');
  await page.locator('#contact-email').fill('qa@example.com');
  await page.locator('#contact-message').fill('Testing encoded text: & plus + and a new line\nSecond line.');
  await page.getByRole('button',{name:'Create email draft'}).click();
  await page.locator('#email-draft').waitFor({state:'visible'});
  const mailto = await page.locator('#email-draft').getAttribute('href');
  assert.ok(mailto.startsWith('mailto:'));
  assert.ok(decodeURIComponent(mailto).includes('Testing encoded text: & plus +'));
  report.checks.push('Contact email draft encoding and honest status');
  await page.goto(origin + 'unknown-page/');
  assert.equal(await page.locator('h1').textContent(),'404');
  await page.getByRole('link',{name:'Back to home'}).click();
  assert.equal(new URL(page.url()).pathname,info.base);
  report.checks.push('404 recovery');
  const plain = await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
  const nojs = await plain.newPage();
  await nojs.goto(origin + 'apps/');
  assert.equal(await nojs.locator('#primary-nav').isVisible(),true);
  assert.equal(await nojs.locator('[data-app]:visible').count(),info.appCount);
  report.checks.push('No-JavaScript navigation and app catalog');
  assert.deepEqual(errors,[]);
  report.checks.push('No browser JavaScript errors');
  fs.writeFileSync(path.join(__dirname,'qa/browser-report.json'),JSON.stringify(report,null,2));
  await browser.close();
  console.log(JSON.stringify(report,null,2));
})().catch(error=>{console.error(error);process.exit(1)});
